= DukeCon Docker Images
:author: Gerd Aschemann <gerd@aschemann.net>

Create some special Docker images for the https://dukecon.org[DukeCon project].

* We use some of them (<<sec:maven>> and <<sec:node>>) for build and test purposes (including Selenium e2e tests),
* <<sec:httpd-base>> is a generic base image for Apache HTTPD based services,
* <<sec:httpd-edge>> is the DukeCon edge service which simplifies composition of DukeCon installations.

Compose a current release

  docker-compose build [ dukecon-httpd-base | dukecon-httpd-edge | dukecon-maven | dukecon-node ]

Push the current version to Docker Hub by

  docker-compose push [ dukecon-httpd-base | dukecon-httpd-edge | dukecon-maven | dukecon-node ]

[[sec:httpd-base]]
== HTTPD-Base

Base Image for DukeCon HTTPD services (e.g., https://github.com/dukecon/dukecon_pwa), based on image
`library/httpd:alpine` with current Apache HTTPD (2.4.7 as of 2017-12-30).

[[sec:httpd-edge]]
== HTTPD-Edge

The DukeCon edge service image can serve as a central dispatcher for DukeCon, e.g., as shown in
<<fig:httpd-edge-sample>>. It is based on <<sec:httpd-base>>.

[[fig:httpd-edge-sample]]
[plantuml, httpd-edge-sample, svg]
.DukeCon Sample Edge Composition
plantuml::images/httpd-edge-sample.puml[,svg]

It serves as an HTTP reverse proxy, forwarding all requests

* to REST and health check URIs to https://github.com/dukecon/dukecon_server[DukeCon-Server]
* everything else to https://github.com/dukecon/dukecon_pwa[DukeCon PWA], the default DukeCon single page application.

[[sec:maven]]
== Maven

It is based on Docker image `library/maven:slim` with the latest Maven version (3.5.2 as of 2017-12-28) based on a slim
line Debian 9.

Run the current release in your (Maven) project root by, e.g.,

  docker run -it --rm \
    -v "$HOME/.m2:/root/.m2" \
    -v "$PWD":/usr/src \
    -w /usr/src \
    dukecon/dukecon-maven:latest \
    mvn clean verify

[[sec:node]]
== Node

It is based on Docker `library/node:slim` with  Node (8.9.3) and NPM (5.5.1, as of 2017-12-30 based on a slim line
Debian 8, which by default only can install a JDK 7. A JDK 8 is needed to run a current Selenium, so we install it from
jessie-backports.

Run the current release in your (Node) project root by e.g.,

  docker run -i ${tty_option} --rm \
    -v "$PWD":/usr/src \
    -w /usr/src \
    --privileged \
    --cap-add=SYS_ADMIN \
    dukecon/dukecon-node:latest \
    /bin/sh -c "npm install && npm run build && npm run unit"
