FROM dukecon/dukecon-httpd-base:latest
MAINTAINER Gerd Aschemann <gerd@aschemann.net>

VOLUME /data/rest

ADD dispatcher.conf /usr/local/apache2/sites.d/dispatcher.conf
ADD modules.conf /usr/local/apache2/conf/local/modules.conf
