FROM dukecon/dukecon-httpd:latest
MAINTAINER Gerd Aschemann <gerd@aschemann.net>

ADD dispatcher.conf /usr/local/apache2/sites.d/dispatcher.conf
ADD modules.conf /usr/local/apache2/conf/local/modules.conf